/**
 * Banned flat positive adjectives for the Slop Detector.
 *
 * Per Requirement 5.5 and design.md → "Stage 8 — Slop Detector":
 * commentary that contains any of these as a whole word
 * (case-insensitive) is rejected as slop and replaced with a line
 * from the Fallback Commentary Library.
 *
 * The list is the brand-tone deny list. These are the colorless,
 * generic, evaluation-light adjectives a tone-deaf model reaches for
 * when it has nothing specific to say. The Slop Detector is the
 * difference between commentary that feels brand-defining and
 * commentary that feels like it was generated by a vending machine.
 *
 * Matching rules (enforced in `slop-detector.ts`):
 * - Whole-word match only — "great" must reject "looks great." but
 *   not "ingratiate" or "greatness".
 * - Case-insensitive — "Great", "GREAT", and "great" all match.
 * - Apply BEFORE punctuation strip so "great." still hits.
 *
 * The five examples called out by Requirement 5.5 are mandatory:
 * `great`, `nice`, `amazing`, `awesome`, `cool`. They appear at the
 * head of the list for visual auditability.
 *
 * NOTE: Hyperbolic dramatic adjectives we intentionally KEEP (so the
 * fallback library and few-shot prompts can use them) include
 * "menacing", "luminous", "feral", "molten", "incandescent",
 * "sovereign", "unhinged", "uncanny". They are not on this list.
 */
export const BANNED_WORDS = [
  // Five required examples from Requirement 5.5 — DO NOT REMOVE.
  "great",
  "nice",
  "amazing",
  "awesome",
  "cool",

  // Generic positives.
  "good",
  "wonderful",
  "fantastic",
  "terrific",
  "lovely",
  "pleasant",
  "delightful",
  "charming",
  "neat",
  "fine",
  "okay",
  "decent",
  "alright",

  // Magnitude inflators that say nothing specific.
  "incredible",
  "unbelievable",
  "remarkable",
  "extraordinary",
  "outstanding",
  "exceptional",
  "phenomenal",
  "spectacular",
  "stunning",
  "breathtaking",
  "marvelous",
  "fabulous",
  "splendid",
  "superb",
  "magnificent",
  "majestic",
  "grand",
  "epic",

  // Hype-fillers commonly returned by tuned-positive models.
  "perfect",
  "flawless",
  "impressive",
  "striking",
  "dazzling",
  "brilliant",
  "fascinating",
  "interesting",
  "captivating",
  "engaging",
  "compelling",

  // Vague intensity / texture words.
  "beautiful",
  "gorgeous",
  "pretty",
  "elegant",
  "stylish",
  "classy",
  "fresh",
  "clean",
  "sleek",
  "smooth",
  "vibrant",
  "lively",

  // Casual approval slang.
  "dope",
  "sick",
  "rad",
  "swell",
  "wicked",
  "killer",
  "legit",
  "solid",
  "tight",
] as const satisfies readonly string[];

/**
 * Type alias for a banned word. Useful for narrow signatures inside
 * `slop-detector.ts` and for typed unit-test fixtures.
 */
export type BannedWord = (typeof BANNED_WORDS)[number];
